package_name: regression_model

training_data_file: train.csv
test_data_file: test.csv 

target: SalePrice

pipeline_name: regression_model 
pipeline_save_file: regression_model_output_v

test_size: 0.1
random_state: 0

features:
  - MSSubClass
  - MSZoning
  - Neighborhood
  - OverallQual
  - OverallCond
  - YearRemodAdd
  - RoofStyle
  - MasVnrType
  - BsmtQual
  - BsmtExposure
  - HeatingQC
  - CentralAir
  - FirstFlrSF
  - GrLivArea
  - BsmtFullBath
  - KitchenQual
  - Fireplaces
  - FireplaceQu
  - GarageType
  - GarageFinish
  - GarageCars
  - PavedDrive
  - LotFrontage
  - YrSold

categorical_features:
  - MSZoning
  - Neighborhood
  - RoofStyle
  - MasVnrType
  - BsmtQual
  - BsmtExposure
  - HeatingQC
  - CentralAir
  - KitchenQual
  - FireplaceQu
  - GarageType
  - GarageFinish
  - PavedDrive

numerical_features:
  - FirstFlrSF
  - GrLivArea
  - LotFrontage

discrete_features:
  - MSSubClass
  - OverallQual
  - OverallCond
  - BsmtFullBath
  - Fireplaces
  - GarageCars

temporal_features:
  - YearRemodAdd
  - YrSold

categorical_features_with_missing:
  - MasVnrType
  - BsmtQual
  - BsmtExposure 
  - FireplaceQu
  - GarageType
  - GarageFinish

numerical_features_with_missing:
  - LotFrontage

features_to_rename:
  1stFlrSF: FirstFlrSF